#! /bin/sh
# 2013/11/15, sunsd
confirm()
{
    echo "$@" >&2
    echo -n "Continue? [y/n/? ] (n): " >&2
    read ANS
    case "$ANS" in
        y|yes|Yes|YES)
            exit 0;;
        [nN]*)
            exit 1;;
        *)
            # default is n
            exit 1;;
    esac
}
confirm "$@"
