#!/bin/sh
# 2012/12/12, sunsd
pdirname()
{
    dir=/project/$PROJ/ccsrc
    if [ "$PROJ" = "" ]; then
        echo "Warning: PROJ is null! Reset..." >&2
        dir=$(cd2 3)
        if [[ $dir = /ccsrc* ]]; then
            dir=$(cd2 1)
        elif [[ $dir != */ccsrc* ]]; then
            echo "Error: None possible value for PROJ!" >&2
            exit 1
        fi
        echo "PROJ=$dir" >&2
    fi
    echo $dir
}
pdirname
