#!/bin/sh
# 2012/12/12, sunsd
# print the root work directory of the project
pdirname()
{
    dir=/project/$PROJ/ccsrc
    if [ "$PROJ" = "" ]; then
        echo "Warning: env PROJ is null!" >&2
        dir=$(ct 4)
        if [[ $dir = /ccsrc* ]]; then
            dir=$(ct 2)
        elif [[ $dir != */ccsrc* ]]; then
            echo "Error: none possible value for PROJ!" >&2
            exit 1
        fi
        echo "Automatically set PROJ dir = { $dir }" >&2
    fi
    if [ -d $dir ]; then
        echo $dir
    else
        echo "project $PROJ does not exist!" >&2
        exit 1
    fi
}
pdirname
