#!/bin/sh
# 2013/12/13, sunsd
# sc, differ from cs, switch between the project's work dir and the install dir

module=$MOD
if [ $# -gt 0 ]; then
    module=$1
fi
pwd=`pwd`
instdir=$(inst $module)
moddir=$(pd)/$module

if [[ "$pwd" = ${CCRUN}/* ]]; then
    cmd="cd $moddir/${pwd#$instdir}"
else
    cmd="cd $instdir/${pwd#$moddir}"
fi
eval $cmd
