#!/bin/sh
# 2013/12/02, sunsd

f=$1
pwd=`pwd`
module=$MOD
if [ "${f:0:1}" != "/" ]; then
    f="$pwd/$f"
fi
if [[ "$f" = */$module* ]]; then
    INSTDIR=$(inst $module)
    [ $? -ne 0 ] && exit 1
    cmd=".dosu cp $f $INSTDIR/${f#*$module/}"
    echo $cmd
    eval $cmd
    [ $? -eq 0 ] && echo "[7mDone.[0m"
else
    echo "Error: Path is not valid!" >&2
fi
