#!/bin/sh
# 2013/12/02, sunsd

f=$1
if [ "${f:0:1}" != "/" ]; then
    f="`pwd`/$f"
fi
INSTDIR=$CCRUN/htdocs/webframes6
cmd=".dosu cp $f $INSTDIR/${f#*webframe/}"
echo $cmd
eval $cmd
if [ $? -eq 0 ]; then
    echo "[7mDone.[0m"
fi
